spring:
    datasource:
        url: "jdbc:mysql://localhost/motocatalogdb"
        username: develop123
        password: develop123
    sql:
        init:
            mode: always
            encoding: UTF-8
logging:
    level:
        root: info
    file:
        name: app.log
    logback:
        rollingpolicy:
            max-file-size: 1MB
mybatis:
    configuration:
        map-underscore-to-camel-case: true
